# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run notion2velog.py
      run: |
        pyinstaller -w -F notion2velog.py
    - name: version env
      run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
      id: extract_version_name 
    - name: Release create
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with: 
        tag_name: ${{ steps.extract_version_name.outputs.version }} 
        release_name: ${{ steps.extract_version_name.outputs.version }}
        body: |
          해당 실행파일과 실행파일로 인해 생성되는 *.pkl은 같은 폴더에 있어야합니다.(초기 로그인 뒤 자동로그인을 위한 사항입니다.)<br><br>
          Release 탭에 에 있는 .exe 파일은 이유는 모르겠지만 실행이 불가능합니다.<br>
          .zip 파일은 받은 뒤 dist 폴더에 있는 .exe 파일을 실행해주세요.<br>
          
          이미지 업로드 칸이 있지만, 개발 중 입니다. ⏰<br><br>
    - name: Upload Executable as Release Asst
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/notion2velog  # 실행 파일 경로
        asset_name: notion2velog.exe  # 업로드될 파일 이름
        asset_content_type: application/octet-stream
